

NAME = Scramble
PROGNAME = $(NAME).java

all: $(PROGNAME)

$(PROGNAME):
	echo "make Words.java"
	javac Words.java
clean:
	rm *.class
fclean: 

run:
	java Words.java

rerun:
	javac $(PROGNAME)
	java $(PROGNAME)

